### ISSUE TITLE
Does this one works ?

### ISSUE THREAD

**Issue by incyi** [harmon25/raspcontrol#1]
Does this one works out of the box with the latest raspberry pi image ?

**Comment by harmon25** [comment]
it should work on any raspberry pi image. 
not really out of the box...still need to install and configure PHP + a webserver

Keep an eye on my pipanel repository...recreating raspcontrol with flask(Python) instead of PHP - should be easier to configure and maintain. A work in progress...

**Comment by johnvick** [comment]
Just tried this with BananaPi running latest  Bananian OS and works OK as far as I can tell.

**Comment by MeganerdNL** [comment]
It works OK!
