### ISSUE TITLE
"Diese Website ist nicht erreichbar" pleace help

### ISSUE THREAD

**Issue by padhie** [harmon25/raspcontrol#11]
I try since days to install raspcontroll on my pi3 and try the introduction vom this repo and some site i found on google... 
Even i get "Diese Website ist nicht erreichbar"

Can pleace help me anyone? i dont know what i do wrong or can do to fix it... 
Other web app's works fine (i try with uninstall all other web apps, same result).

**Comment by harmon25** [comment]
Will need more information to help debug.
What OS version are you running? Raspbian? 

Sounds like a configuration issue.

**Comment by harmon25** [comment]
Inactive - closing
