### ISSUE TITLE
unable to get raspcontrol working

### ISSUE THREAD

**Issue by okgan** [harmon25/raspcontrol#12]
Hey, I'm on Raspbian GNU/Linux 8 (jessie).  I just ran these commands:
```
cd /var/www/html
sudo git clone https://github.com/harmon25/Raspcontrol.git raspcontrol
sudo chown -R www-data:www-data raspcontrol/
sudo mkdir /etc/raspcontrol
sudo nano /etc/raspcontrol/database.aptmnt
<<added in the info in the README.md file>>
sudo chmod -R 755 /etc/raspcontrol/database.aptmnt
sudo chown -R www-data:www-data /etc/raspcontrol
```

and then went to:
<Pi's IP address>/raspcontrol
and I see nothing..?

**Comment by harmon25** [comment]
Do you have apache installed?
Is it configured to serve up `/var/www/data`?
Do you have PHP enabled on apache?

Will need more info...also have not tested this in a while so could be broken

**Comment by okgan** [comment]
Hey, so I am using lighttpd, configured to serve from /var/www, with PHP enabled.   I tried /var/www/data but couldn't get things working.   Since then I've switched to another packaged and stopped trying to get raspcontrol to work.   I'm not certain, but I think raspcontrol is broken...
