### ISSUE TITLE
Failed to open authentification file in /etc/raspcontrol/database.aptmnt

### ISSUE THREAD

**Issue by ghost** [harmon25/raspcontrol#2]
Failed to open authentification file in /etc/raspcontrol/database.aptmnt on:

Raspberry Pi 1 B with Raspbian
Raspberry Pi 1 B+ with Raspbian
Raspberry Pi 2 B with Raspbian

**Comment by magarto** [comment]
If using Nginx, have you added /etc/raspcontrol/ to the open_basedir in php.ini and restarted php service???

**Comment by harmon25** [comment]
Did you create the database.aptmnt as described in the readme?

**Comment by vesrah** [comment]
I came across this issue and found that the same error is reported if there is a syntax error in the database.aptmnt JSON

1. Make sure that www-data can access the /etc/raspcontrol folder and the /etc/raspcontrol/database.aptmnt file.
2. Check database.aptmnt for JSON syntax errors (missing comma is easy to overlook)
