### ISSUE TITLE
File does not exist - css/images

### ISSUE THREAD

**Issue by Bobbaone** [harmon25/raspcontrol#3]
I got a Apache Servererror:

File does not exist: /var/www/raspcontrol/css/images, referer: http://raspberrypi/raspcontrol/css/jquery-ui.css

Any Fixes?

I didnt find a fix or this file here in the repository.

Thanks :)

**Comment by harmon25** [comment]
hmm the jquery-ui css file is referencing some images at that location, the browser is trying to download them as assets, and apache doesn't know what to do - might be better to pull all JS/CSS libs from a CDN if you have internet access...

I included those libs in the project in case it was being run offline...
